services:
  db:
    image: postgres:17.2-alpine
    container_name: vegetable-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  dev:
    container_name: vegetable-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /workspace
    tty: true
    stdin_open: true
    networks:
      - dev
    ports:
      - ${APP_PORT}:8080 #go
      - ${CLIENT_PORT}:3000 #react native
    user: "node"
    volumes:
      - ./:/workspace
      - node_modules:/client/node_modules
    depends_on:
      - db

volumes:
  node_modules:
    external: false
  postgres_data:

networks:
  dev:
    driver: bridge
