name: Manage Project

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  check-reviewers:
    runs-on: ubuntu-latest
    outputs:
      column: ${{ steps.set.outputs.column }}
    steps:
      - name: Determine column from reviewers
        id: set
        run: |
          REVIEWERS_COUNT=$(echo "${{ toJson(github.event.pull_request.requested_reviewers) }}" | jq 'length')
          if [ "$REVIEWERS_COUNT" -gt 0 ]; then
            echo "column=PR:InReview" >> "$GITHUB_OUTPUT"
          else
            echo "column=PR:Approved" >> "$GITHUB_OUTPUT"

  pr-project:
    needs: check-reviewers
    uses: ./.github/workflows/pr-assignment-to-project.yml@dev
    with:
      ProjectNumber: 1
      RepositoryName: ${{ github.repository }}
      PRNumber: ${{ github.event.pull_request.number }}
      HTML_URL: ${{ github.event.pull_request.html_url }}
      FieldKeyValues: '[{ "key": "Status", "value": "${{ needs.check-reviewers.outputs.column }}" }]'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
